### PR TITLE
Serverless functions development 001 james

### PR DESCRIPTION
**Pull request by Jamesllllllllll**
This implements a serverless function for calling the Weather API, which now completely hides the API key.

I also wrote a README located in /api that documents how to implement a serverless function.

TO DOs:

- ~~Implement Serverless Function for fetching city names~~ Done!
- Store the selected city in localstorage so it 'remembers' when user returns
- ~~Hide city select form when submitted~~ Done!
- Gracefully transition from form to displaying weather, with placeholders or animations so the text does not "jump" around
- Add city selector to settings screen so it can be changed after it's first set
- Restructure HTML and add CSS

### CODE REVIEW

**Review by musiked7 — COMMENTED** [review]
Great work!

**Review by where-is-brett — COMMENTED** [review]
Great work James! Everything looks good to me. I only have one minor suggestion. 

In  `src/features/weather/Weather.jsx`, it is possible to remove the `showWeather` state and use `weather` state to check whether the form/icon should display. This can be achieved by reinitialising the `weather` state to default when the change city button is clicked (when `changeCity()` is called). 

Cheers
Brett

**Comment by Jamesllllllllll** [comment]
> Great work James! Everything looks good to me. I only have one minor suggestion.
> 
> In `src/features/weather/Weather.jsx`, it is possible to remove the `showWeather` state and use `weather` state to check whether the form/icon should display (weather===defaultValue ? display form : display icon). This can be achieved by reinitialising the `weather` state to default when the change city button is clicked (when `changeCity()` is called).
> 
> Cheers Brett

Thank you, Brett! I've made the changes, and also reset all state when changing cities just to clean it up.

One thing perhaps you could ponder with me - I tried the conditional rendering like so:

```js
{(weather === defaultWeather) ? (
  <form...
```

The page loads correctly with the city form, but once one character is entered (the component's first re-render with form input) it switches to display the weather.

I'm curious why setting the default state to `defaultWeather` and checking if `weather === defaultWeather` would return false.

This does work:

```js
(weather.location.name === "") ? (
  <form...
```

**Review by where-is-brett — COMMENTED** [review]
My bad! I should not have referenced strict equality because we are comparing JavaScript objects! 

`weather===defaultWeather` checks if the two object references are pointing to the exact same object in memory. Although they may have the same properties and values, they are two different objects! 

Instead, we can check the stringified version of those two objects: 

`JSON.stringify(weather)===JSON.stringify(defaultWeather)`

Here, the `===` comparison checks if the two string values are exactly the same.

**Comment by Jamesllllllllll** [comment]
> My bad! I should not have referenced strict equality because we are comparing JavaScript objects!
> 
> `weather===defaultWeather` checks if the two object references are pointing to the exact same object in memory. Although they may have the same properties and values, they are two different objects!
> 
> Instead, we can check the stringified version of those two objects:
> 
> `JSON.stringify(weather)===JSON.stringify(defaultWeather)`
> 
> Here, the `===` comparison checks if the two string values are exactly the same.

Amazing, thank you! I remember learning this but apparently it didn't sink in :) Fixed!

**Pull request merged**
